language: python
python:
  - "2.7"
jdk:
  - openjdk7
virtualenv:
  system_site_packages: true
install:
  # Install Spark
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-0.9.1-incubating-bin-hadoop1.tgz
  - tar -xzf spark-0.9.1-incubating-bin-hadoop1.tgz
  - sudo apt-get install -qq python-numpy python-scipy python-imaging python-sklearn
  - pip install -r python/requirements.txt
  # Workaround for Travis issue with POSIX semaphores; see
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
script:
    - export SPARK_HOME=`pwd`/spark-0.9.1-incubating-bin-hadoop1
    - cd python/test
    - ./run_tests.sh
